apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # CORRECTIF : manquant - sans cette source, impossible d'afficher directement
  # les tables Gold (daily_market_kpi, price_prediction_result...) dans Grafana
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: crypto_gold
    user: crypto
    secureJsonData:
      password: crypto123
    jsonData:
      sslmode: disable
      postgresVersion: 1500